// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa7D0thVtYmWoqpm32MdVeUY9KCMlGeOg',
    appId: '1:455571629756:web:3c94e24802da04d337d2b9',
    messagingSenderId: '455571629756',
    projectId: 'pharmacy-d3630',
    authDomain: 'pharmacy-d3630.firebaseapp.com',
    storageBucket: 'pharmacy-d3630.appspot.com',
    measurementId: 'G-EDTRZKRPLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASYF-75UfGNRM_7frF_xraXqv_-z3EEVU',
    appId: '1:455571629756:android:229f85f9445c350337d2b9',
    messagingSenderId: '455571629756',
    projectId: 'pharmacy-d3630',
    storageBucket: 'pharmacy-d3630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW0bMeADLHpBA7U5KJDNaM_IFDcxMqo7Q',
    appId: '1:455571629756:ios:7404fe720da9a4dc37d2b9',
    messagingSenderId: '455571629756',
    projectId: 'pharmacy-d3630',
    storageBucket: 'pharmacy-d3630.appspot.com',
    iosBundleId: 'com.example.pharmacyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW0bMeADLHpBA7U5KJDNaM_IFDcxMqo7Q',
    appId: '1:455571629756:ios:7404fe720da9a4dc37d2b9',
    messagingSenderId: '455571629756',
    projectId: 'pharmacy-d3630',
    storageBucket: 'pharmacy-d3630.appspot.com',
    iosBundleId: 'com.example.pharmacyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa7D0thVtYmWoqpm32MdVeUY9KCMlGeOg',
    appId: '1:455571629756:web:19861dbaab2055c337d2b9',
    messagingSenderId: '455571629756',
    projectId: 'pharmacy-d3630',
    authDomain: 'pharmacy-d3630.firebaseapp.com',
    storageBucket: 'pharmacy-d3630.appspot.com',
    measurementId: 'G-9ZBFBGK0B6',
  );
}
